name: CI

on:
  - pull_request

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      examples: ${{ steps.list_examples.outputs.examples }}
    name: Pre
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: List examples
        id: list_examples
        run: .github/script/examples

  unit:
    needs: pre
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: release
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
    name: Unit / Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake spec

  acceptance:
    needs:
      - pre
      - unit
    runs-on: ubuntu-latest
    env:
      BEAKER_setfile: debian10-64
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
        example: ${{ fromJson(needs.pre.outputs.examples) }}
    name: Acceptance / Ruby ${{ matrix.ruby }} - ${{ matrix.example }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: examples/${{ matrix.example }}
      - name: Run tests
        run: bundle exec rake beaker
        working-directory: examples/${{ matrix.example }}
